# Generated by Django 3.1.5 on 2022-06-22 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220621_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 9, 32, 3, 860131, tzinfo=utc)),
        ),
    ]
